### ISSUE TITLE
supabase.auth.sign_in_with_otp with phone login throws error 

### ISSUE THREAD

**Issue by hgseo16** [supabase-community/gotrue-py#321]
**Describe the bug**
While the following function `supabase.auth.sign_in_with_otp(params={"phone": phone, "token": verification_code, "type": "sms"})` successfully sends an OTP to the phone number described, the request returns the following error.

```
.
.
.
  File "/Users/zzan/Desktop/repositories/zzan-backend-fastapi/./app/routers/users.py", line 23, in post_signin_phone
    data = supabase.auth.sign_in_with_otp(credentials={"phone": phone})
  File "/Users/zzan/Desktop/repositories/zzan-backend-fastapi/venv/lib/python3.9/site-packages/gotrue/_sync/gotrue_client.py", line 299, in sign_in_with_otp
    return self._request(
  File "/Users/zzan/Desktop/repositories/zzan-backend-fastapi/venv/lib/python3.9/site-packages/gotrue/_sync/gotrue_base_api.py", line 119, in _request
    raise handle_exception(e)
gotrue.errors.AuthRetryableError: 5 validation errors for User
id
  field required (type=value_error.missing)
app_metadata
  field required (type=value_error.missing)
user_metadata
  field required (type=value_error.missing)
aud
  field required (type=value_error.missing)
created_at
  field required (type=value_error.missing)
```

**To Reproduce**
```
from supabase import create_client, Client

url: str = "SUPABASE_API_URL"
key: str = "SUPABASE_API_KEY"
supabase: Client = create_client(url, key)

phone: str = "PHONE_NUMBER_WITH_COUNTRY_CODE"

data = supabase.auth.sign_in_with_otp(credentials={"phone": phone})
print(data)
```

**Expected behavior**
Should return an AuthResponse class.

```
class AuthResponse(BaseModel):
    user: Union[User, None] = None
    session: Union[Session, None] = None
```

**Screenshots**
![Screenshot 2023-04-07 at 5 47 33 PM](https://user-images.githubusercontent.com/56215649/230576543-4f6e5dce-bb93-49cf-bbef-673046eea914.png)

**Environment (please complete the following information):**
- Python: 3.9.6
- OS: macOS Ventura (v. 13.2.1)

**Additional context**
It seems that there is an issue occurring when the `sign_in_with_otp` function is called. The problem seems to be happening when the function tries to return the result of `self._request(...)`, which is a function call in the `gotrue_base_api.py` module. When the `_request` function is called, the result variable is an empty dictionary {} which may be causing an issue during the `parse_auth_response` function invocation in the gotrue package.

Let me know what you guys think! I would love to try to help debug this issue as well.

**Comment by silentworks** [comment]
Closing this as fixed as there hasn't been any reports of this issue persisting in newer versions of the library.

**Comment by lucas-vitrus** [comment]
Getting the same error..

```
AuthRetryableError
gotrue.errors.AuthRetryableError: 5 validation errors for User
id
  Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
app_metadata
  Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
user_metadata
  Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
aud
  Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
created_at
  Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing

Traceback (most recent call last)
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/gotrue/_sync/gotrue_base_api.py", line 116, in _request
return xform(result)
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/gotrue/helpers.py", line 66, in parse_auth_response
user = model_validate(User, user_data) if user_data else None
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/gotrue/helpers.py", line 28, in model_validate
return model.model_validate(contents)
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/pydantic/main.py", line 504, in model_validate
return cls.__pydantic_validator__.validate_python(
During handling of the above exception, another exception occurred:
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
response = self.handle_exception(e)
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/Users/lucascassiano/Documents/GitHub/vitrus-ai-vision/gateway-server/./src/main.py", line 330, in user_sign_in
data = supabase.auth.sign_in_with_otp({'phone': phone_number})
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/gotrue/_sync/gotrue_client.py", line 306, in sign_in_with_otp
return self._request(
File "/Users/lucascassiano/.local/share/virtualenvs/gateway-server-1zd7_S6J/lib/python3.10/site-packages/gotrue/_sync/gotrue_base_api.py", line 118, in _request
raise handle_exception(e)
gotrue.errors.AuthRetryableError: 5 validation errors for User
id
Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.3/v/missing
app_metadata
Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.3/v/missing
user_metadata
Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.3/v/missing
aud
Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.3/v/missing
created_at
Field required [type=missing, input_value={'message_id': 'SM724b22e...ecc8ff615e0406e1d92cf8'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.3/v/missing
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by J0** [comment]
Ah yeah this is probably from the new `message_id` field - let's track this on a separate issue

**Comment by athon-millane** [comment]
@J0 I'm still encountering the issue as well - was the separate issue ever created?

**Comment by J0** [comment]
Hey @athon-millane,

I don't think it was, sorry about that. Thanks for flagging this
